"""init - songs and plays

Revision ID: 37ed01765b38
Revises: 
Create Date: 2019-02-10 01:27:18.630190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ed01765b38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('songid', sa.String(length=64), nullable=False),
    sa.Column('artist', sa.String(length=64), nullable=True),
    sa.Column('songname', sa.String(length=64), nullable=True),
    sa.Column('album', sa.String(length=64), nullable=True),
    sa.Column('player_specific_id', sa.String(length=64), nullable=True),
    sa.Column('thumb', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('songid')
    )
    op.create_index(op.f('ix_song_player_specific_id'), 'song', ['player_specific_id'], unique=True)
    op.create_table('play',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songid', sa.String(length=64), nullable=False),
    sa.Column('timefrom', sa.String(length=64), nullable=True),
    sa.Column('timeto', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['songid'], ['song.songid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_songid'), 'play', ['songid'], unique=False)
    op.create_index(op.f('ix_play_timefrom'), 'play', ['timefrom'], unique=False)
    op.create_index(op.f('ix_play_timeto'), 'play', ['timeto'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_timeto'), table_name='play')
    op.drop_index(op.f('ix_play_timefrom'), table_name='play')
    op.drop_index(op.f('ix_play_songid'), table_name='play')
    op.drop_table('play')
    op.drop_index(op.f('ix_song_player_specific_id'), table_name='song')
    op.drop_table('song')
    # ### end Alembic commands ###
